# Generated by Django 5.1.6 on 2025-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('date_she', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('no_tokens', models.IntegerField()),
            ],
        ),
    ]
