# Generated by Django 5.1.6 on 2025-03-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_sheduler'),
        ('predict', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.user'),
        ),
        migrations.AlterField(
            model_name='sheduler',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.user'),
        ),
    ]
