# Generated by Django 5.1.6 on 2025-03-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_userid_alter_sheduler_userid'),
        ('predict', '0016_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.sheduler')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.user')),
            ],
        ),
    ]
