# Generated by Django 5.1.6 on 2025-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
