# Generated by Django 5.1.6 on 2025-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_leave_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_doctor',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
