# Generated by Django 5.1.6 on 2025-03-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_alter_doctor_userid_alter_sheduler_userid'),
        ('predict', '0016_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.sheduler')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.user')),
            ],
        ),
    ]
