# Generated by Django 5.1.6 on 2025-03-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('predict', '0017_rename_name_diagnostictest_patid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='predict.user')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='predict.user')),
            ],
        ),
    ]
