# Generated by Django 5.1.6 on 2025-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_appointment_doctor_doctor_availability_presecription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
