# Generated by Django 5.1.6 on 2025-03-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='doctor_availability',
        ),
        migrations.DeleteModel(
            name='Presecription',
        ),
    ]
