# Generated by Django 5.1.6 on 2025-03-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
