# Generated by Django 5.1.6 on 2025-03-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0016_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostictest',
            old_name='name',
            new_name='patid',
        ),
    ]
